/**
 * Metadonnees SEO des articles : titre, description, dates, FAQ.
 *
 * Source unique. Trois consommateurs :
 *   - layout.tsx  : generateStaticParams (quelles pages construire) + <meta> + JSON-LD
 *   - sitemap.ts  : quelles URLs declarer a Google, et leur lastModified
 *   - (a venir)   : la liste affichee sur /blog
 *
 * Ajouter un article ICI suffit a le faire construire ET declarer au sitemap.
 * Avant, les deux listes etaient tenues a la main separement : un oubli cote
 * sitemap rendait l'article invisible pour Google.
 *
 * ATTENTION : `date` (publication) doit correspondre a la date AFFICHEE sur la
 * page. Google exige que les donnees structurees refletent le contenu visible.
 */

export type ArticleSeo = {

  title: string
  description: string
  keywords: string
  date: string
  dateModified: string
  category: string
  faq: { q: string; a: string }[]
}

export const seoData: Record<string, ArticleSeo> = {
  'cout-avis-google-comparatif': {
    title: "Combien coûte un avis Google ? Le vrai coût par avis",
    description: "Combien coûte réellement un avis Google ? Comparatif du coût par avis de 6 méthodes de collecte, coût caché du temps salarié et calcul détaillé sur 36 mois.",
    keywords: 'cout avis google, prix avis google, combien coute un avis google, cout par avis, acheter avis google, plateforme avis google prix, collecte avis google tarif, roi avis google',
    date: '2026-08-05',
    dateModified: '2026-08-05',
    category: 'Comparatif',
    faq: [
      { q: 'Combien coûte un avis Google en moyenne ?', a: "Entre 0,03 € et 1,50 € selon la méthode de collecte, temps de personnel inclus, sur une période de 36 mois. Les supports physiques sans abonnement se situent en bas de fourchette (0,03 à 0,15 €), les plateformes SMS ou e-mail en haut (0,44 à 1,50 €). Un avis ne s'achète pas : ces montants sont des coûts de collecte, pas un prix d'achat, qui serait interdit par Google et sanctionné en droit français." },
      { q: "Quel est le coût par avis d'une plaque NFC ?", a: "Environ 0,06 € par avis sur 36 mois pour le matériel seul, et 0,12 € en incluant les 4 à 6 secondes de temps salarié par client. Le calcul repose sur un achat unique de 35,88 € à 107,88 € selon le pack, sans aucun frais récurrent, et sur un taux de collecte de 25 à 45 % selon le secteur et l'emplacement." },
      { q: "Les plateformes d'avis par SMS valent-elles leur abonnement ?", a: "Elles se justifient dans deux cas : un modèle sans contact physique en fin de prestation, comme la vente à distance, ou un besoin de reporting multi-établissements. Pour un commerce de proximité avec un passage en caisse, elles coûtent 10 à 25 fois plus cher par avis, produisent 40 % de volume en moins à cause du délai de relance, et exposent au risque de réveiller un client mécontent." },
      { q: 'Peut-on acheter des avis Google ?', a: "Non. C'est interdit par les règles de Google, qui procède à des suppressions massives incluant les avis légitimes et peut suspendre la fiche. En France, s'y ajoute la qualification de pratique commerciale trompeuse, passible de 300 000 € d'amende pour une personne morale. Le rapport coût / risque est sans commune mesure avec celui d'une collecte régulière et légitime." },
      { q: 'Faut-il vraiment compter le temps du personnel dans le coût ?', a: "Oui, c'est souvent le premier poste. Une minute de temps salarié chargé revient à environ 0,35 € en 2026. Une méthode demandant 30 secondes par client dans un commerce à 800 clients mensuels coûte 1 680 € par an en temps seul, soit davantage que la plupart des abonnements du marché." },
      { q: 'Combien rapporte un avis Google ?', a: "Entre 4 et 120 € de chiffre d'affaires additionnel selon le secteur et le panier moyen : environ 4 à 9 € en restauration, 7 à 15 € en coiffure, 25 à 60 € en garage automobile et 40 à 120 € chez un artisan du bâtiment. Rapportée à un coût de collecte inférieur à 0,15 €, la rentabilité est d'un ordre de grandeur sans équivalent parmi les leviers marketing d'un commerce local." },
    ],
  },
  'combien-avis-google-pack-local': {
    title: "Combien d'avis Google pour être dans le pack local ?",
    description: "Combien d'avis Google faut-il pour entrer dans le top 3 du pack local ? La méthode de calcul, les benchmarks par secteur et le plan pour atteindre le seuil.",
    keywords: 'combien avis google pack local, nombre avis google referencement local, pack local google, top 3 google maps, avis google classement local, seuil avis google, google business profile classement',
    date: '2026-08-03',
    dateModified: '2026-08-03',
    category: 'Statistiques',
    faq: [
      { q: 'Combien d\'avis Google faut-il pour apparaître dans le pack local ?', a: 'Il n\'existe pas de seuil universel. La règle fiable est la médiane des trois établissements déjà classés sur votre mot-clé, majorée d\'environ 30 %. En pratique, cela représente 20 à 50 avis dans une petite ville, 60 à 150 dans une ville moyenne, et 150 à 400 dans une métropole selon le secteur.' },
      { q: 'Combien de temps faut-il pour entrer dans le pack local ?', a: 'Les premiers mouvements de position apparaissent entre la 4e et la 8e semaine de collecte régulière. Une entrée dans le top 3 demande généralement 3 à 9 mois selon l\'écart de départ et le niveau de concurrence de la zone.' },
      { q: 'Vaut-il mieux beaucoup d\'avis ou une très bonne note ?', a: 'Les deux, mais dans cet ordre : le volume vous rend éligible au classement, la note transforme la visibilité en clics. En dessous de 4,0, le taux de clic s\'effondre. Au-dessus de 4,4, l\'effet marginal d\'un dixième de point supplémentaire devient faible, et une note de 5,0 parfaite paraît même suspecte aux internautes.' },
      { q: 'Les anciens avis comptent-ils toujours ?', a: 'Ils comptent dans le total affiché, mais leur poids diminue fortement avec le temps. Google favorise les fiches actives : visez au moins 10 % de votre volume total d\'avis déposés sur les 90 derniers jours pour maintenir la fraîcheur du signal.' },
      { q: 'La distance peut-elle m\'empêcher d\'entrer dans le pack local ?', a: 'Oui, partiellement. Le classement varie selon la position de l\'internaute : vous pouvez être premier dans un rayon de 500 mètres et absent à 3 kilomètres. Vous ne pouvez pas modifier votre adresse, mais une proéminence forte élargit mécaniquement le rayon sur lequel Google vous affiche.' },
      { q: 'Une plaque NFC accélère-t-elle vraiment la collecte d\'avis ?', a: 'Oui, parce qu\'elle supprime la friction au moment précis où le client est satisfait et a déjà son téléphone en main. Les taux constatés sont de 25 à 45 % selon le secteur et l\'emplacement, contre 8 à 12 % pour un QR code et 1 à 3 % pour une carte de visite. Pour la plupart des commerces, atteindre le seuil du pack local ne demande qu\'un taux de collecte inférieur à 5 %.' },
    ],
  },
  'plaque-nfc-salle-de-sport': {
    title: 'Plaque NFC salle de sport : où la poser, quoi dire',
    description: "Salles de sport, box de CrossFit et studios : collectez des avis Google avec une plaque NFC. Emplacements, moments clés et scripts à donner à l'équipe.",
    keywords: 'plaque nfc salle de sport, avis google salle de sport, plaque nfc fitness, avis google club de fitness, plaque nfc crossfit, seo local salle de sport, avis google coach sportif',
    date: '2026-08-03',
    dateModified: '2026-08-03',
    category: 'Secteur',
    faq: [
      { q: "Combien d'avis Google une salle de sport peut-elle collecter avec une plaque NFC ?", a: "Une salle de 500 à 800 adhérents passe généralement de 4-8 avis/mois à 20-40 avis/mois, soit une multiplication par 4 à 6. Les clubs de plus de 1 500 abonnés équipés de plusieurs plaques dépassent régulièrement 40 avis mensuels. Le facteur déterminant n'est pas la taille de la salle mais le nombre d'emplacements équipés et la systématisation de la demande en fin de cours." },
      { q: 'Où placer la plaque NFC dans une salle de sport ?', a: "Le bureau du coach lors des bilans de suivi affiche le meilleur taux (40-55 %), mais c'est le comptoir d'accueil ou la borne de badgeage qui apporte le volume (30-40 %), car l'adhérent y passe plusieurs fois par semaine avec son téléphone déjà en main. La salle de cours collectifs (25-35 %) est le meilleur complément grâce à l'effet de groupe." },
      { q: 'Comment collecter des avis dans une salle ouverte 24 h/24 sans personnel ?', a: "C'est justement là que la plaque NFC est irremplaçable : elle fonctionne sans intervention humaine. Sur les salles 24 h/24 que nous suivons, plus de 60 % des avis sont déposés en dehors des heures de présence du personnel. Équipez en priorité la borne de badgeage et les zones de sortie, et compensez l'absence de script oral par une signalétique claire." },
      { q: "La plaque résiste-t-elle à l'humidité des vestiaires et aux produits désinfectants ?", a: "Oui. L'acrylique premium 3 mm résiste à l'eau, aux UV, aux rayures et aux produits d'entretien courants. Un coup d'éponge suffit à la nettoyer, contrairement à une affiche papier ou à un flyer plastifié qui gondole en quelques semaines dans un environnement chaud et humide." },
      { q: "Puis-je offrir une séance ou un mois gratuit en échange d'un avis ?", a: "Non, c'est formellement interdit par les règles de Google. Toute contrepartie expose à la suppression massive de vos avis, y compris les avis légitimes, et à la suspension de votre fiche. La plaque NFC fonctionne parce qu'elle supprime la friction, pas parce qu'elle achète l'avis." },
      { q: 'Quel pack de plaques choisir pour une salle de sport ?', a: "Studio de pilates, box de CrossFit ou petite salle mono-accueil : Pack Starter. Salle classique avec accueil et cours collectifs : Pack Business (2 plaques), la configuration la plus fréquente. Club de plus de 800 m², salle ouverte 24 h/24 ou établissement multi-étages : Pack Pro (5 plaques)." },
    ],
  },
  'faux-avis-google-signaler': {
    title: 'Faux avis Google : les signaler et s\'en protéger',
    description: 'Faux avis Google : comment les repérer, les signaler à Google et s\'en protéger. Procédure, délais de suppression et dilution par le volume.',
    keywords: 'faux avis google, signaler faux avis google, supprimer faux avis google, faux avis negatif concurrent, faux avis positifs, se proteger faux avis, faux avis google entreprise',
    date: '2026-07-31',
    dateModified: '2026-07-31',
    category: 'SEO Local',
    faq: [
      { q: 'Google supprime-t-il vraiment les faux avis quand on les signale ?', a: 'Oui, mais pas systématiquement ni immédiatement. Les avis qui enfreignent objectivement les règles (insultes, hors sujet, conflit d\'intérêts démontrable) sont retirés dans 3 à 15 jours avec un bon taux de succès. Un avis négatif simplement désagréable mais crédible a en revanche peu de chances d\'être supprimé : d\'où l\'importance de la stratégie de dilution par le volume de vrais avis.' },
      { q: 'Comment prouver qu\'un avis est faux ?', a: 'Rassemblez un faisceau d\'indices : absence du client dans vos registres, profil auteur sans historique ou créé récemment, contenu vague ou décrivant un service que vous ne proposez pas, avis identiques déposés chez vos concurrents. Une capture d\'écran horodatée de l\'avis et du profil renforce nettement votre dossier auprès du support Google.' },
      { q: 'Que faire si un concurrent poste de faux avis négatifs ?', a: 'Signalez chaque avis pour conflit d\'intérêts, documentez le profil de l\'auteur (surtout s\'il note aussi d\'autres établissements de votre secteur), et escaladez au support avec vos preuves. En parallèle, accélérez la collecte de vrais avis pour rendre l\'attaque inoffensive. Pour les cas graves et répétés, une mise en demeure d\'avocat reste possible.' },
      { q: 'Peut-on acheter des avis positifs pour compenser ?', a: 'Non, jamais. Les faux avis positifs violent les règles de Google et la loi française (pratique commerciale trompeuse, jusqu\'à 300 000 € d\'amende pour une entreprise). Google les détecte par lots et peut suspendre toute votre fiche. La seule voie durable est de collecter de vrais avis, ce qu\'une plaque NFC rend simple et rapide.' },
      { q: 'Combien de temps un faux avis reste-t-il visible ?', a: 'S\'il est supprimé par Google, entre quelques jours et quelques semaines selon le motif. S\'il ne l\'est pas, il reste en ligne indéfiniment — mais une collecte active de vrais avis le repousse en bas de liste en quelques jours, où il devient invisible pour la plupart des visiteurs.' },
      { q: 'Une plaque NFC aide-t-elle vraiment contre les faux avis ?', a: 'Indirectement mais efficacement. Elle ne supprime pas un faux avis, mais elle multiplie vos vrais avis récents par 5 à 10. Sur une fiche riche et fraîche, un faux avis pèse une fraction de pourcent et disparaît sous les avis plus récents. Le volume et la fraîcheur sont la protection la plus fiable qui existe, et la plaque NFC est le moyen le plus simple de les obtenir.' },
    ],
  },
  'plaque-nfc-boulangerie': {
    title: 'Plaque NFC boulangerie : placement et script caisse',
    description: 'Boulangeries et pâtisseries : collectez des avis Google avec une plaque NFC malgré le rush. Guide 2026 : emplacements, scripts, exemples de calcul.',
    keywords: 'plaque nfc boulangerie, avis google boulangerie, plaque nfc patisserie, avis google boulanger, plaque avis google boulangerie patisserie, seo local boulangerie, avis google point chaud',
    date: '2026-07-27',
    dateModified: '2026-07-28',
    category: 'Secteur',
    faq: [
      { q: 'Combien d\'avis Google une boulangerie peut-elle collecter avec une plaque NFC ?', a: 'Une boulangerie recevant 400 à 700 clients par jour passe généralement de 3-6 avis/mois à 30-60 avis/mois, soit une multiplication par 5 à 8. Les boulangeries-pâtisseries avec salon de thé dépassent souvent 45 avis par mois grâce aux emplacements complémentaires.' },
      { q: 'Où placer la plaque NFC dans une boulangerie ?', a: 'Le comptoir de caisse, juste à côté du terminal de paiement, est le meilleur emplacement (40-50 % de conversion) : le client a déjà son téléphone en main pour payer en sans contact. La vitrine de retrait (15-25 %) et les tables du salon de thé (10-20 %) sont d\'excellents compléments.' },
      { q: 'La collecte d\'avis n\'est-elle pas impossible pendant le rush ?', a: 'Justement non : c\'est là que la plaque NFC prend tout son sens. Pendant le coup de feu, elle travaille seule, sans que la vendeuse ait besoin de parler, grâce à l\'emplacement caisse et au téléphone déjà en main. Le script de 3 secondes se réserve aux heures creuses.' },
      { q: 'La plaque résiste-t-elle à la farine et à l\'humidité ?', a: 'Oui. L\'acrylique premium 3 mm résiste à l\'eau, aux UV, aux rayures et aux projections. Un simple coup d\'éponge suffit à la nettoyer, contrairement à une affiche papier ou un flyer plastifié qui gondole vite sur un comptoir de boulangerie.' },
      { q: 'Puis-je offrir une viennoiserie en échange d\'un avis ?', a: 'Non, c\'est formellement interdit par les règles de Google. Vos avis pourraient être supprimés en masse et votre fiche suspendue. La plaque NFC fonctionne en supprimant la friction, pas en achetant l\'avis.' },
      { q: 'Quel pack de plaques choisir pour une boulangerie ?', a: 'Petite boulangerie mono-caisse : Pack Starter. Boulangerie avec deux caisses ou caisse plus comptoir pâtisserie : Pack Business (2 plaques), la configuration la plus courante. Boulangerie-pâtisserie avec salon de thé et comptoir traiteur : Pack Pro (5 plaques).' },
    ],
  },
  'optimiser-fiche-google-business-profile': {
    title: 'Optimiser sa fiche Google Business Profile',
    description: 'Le guide complet 2026 pour optimiser votre fiche Google Business Profile : catégories, photos, avis, Google Posts et pack local. Méthode et plan 30 jours.',
    keywords: 'optimiser fiche google business profile, google business profile, fiche google my business, google business profile avis, pack local google, seo local fiche google, ameliorer fiche google',
    date: '2026-07-24',
    dateModified: '2026-07-28',
    category: 'SEO Local',
    faq: [
      { q: 'La fiche Google Business Profile est-elle gratuite ?', a: 'Oui, totalement. Créer, revendiquer et gérer une fiche Google Business Profile ne coûte rien. Vous ne payez que si vous choisissez de faire de la publicité via Google Ads, ce qui reste facultatif. L\'optimisation décrite dans ce guide est 100 % gratuite.' },
      { q: 'Comment apparaître dans le pack local (les 3 résultats de Google Maps) ?', a: 'Le pack local classe les fiches selon la pertinence (catégorie et services bien choisis), la distance (votre proximité avec l\'internaute) et la notoriété (volume, fraîcheur et note de vos avis). Optimisez votre catégorie principale et collectez des avis réguliers : ce sont les deux leviers sur lesquels vous avez le plus de marge.' },
      { q: 'Combien de photos faut-il sur une fiche Google Business Profile ?', a: 'Visez au moins 15 à 25 photos de qualité (façade, intérieur, équipe, produits ou réalisations) et ajoutez-en de nouvelles chaque mois. Les fiches avec photos reçoivent environ 42 % de demandes d\'itinéraire en plus. Les photos publiées par vos clients pèsent encore plus dans la confiance.' },
      { q: 'Les avis Google influencent-ils vraiment le classement de ma fiche ?', a: 'Oui, c\'est l\'un des trois piliers du classement local. Google regarde le nombre d\'avis, la note moyenne et la fraîcheur (avoir des avis récents). Une fiche qui collecte des avis chaque semaine surperforme une fiche figée, même mieux notée. C\'est le facteur sur lequel vous pouvez le plus agir.' },
      { q: 'À quelle fréquence faut-il publier des Google Posts ?', a: 'Un post par semaine est un bon rythme. Les Google Posts (hors offres) expirent au bout de 7 jours, donc la régularité compte. Ils envoient un signal de fraîcheur à Google et poussent le prospect à l\'action directement depuis votre fiche.' },
      { q: 'Combien de temps pour voir des résultats après avoir optimisé sa fiche ?', a: 'Les premiers effets (plus de vues, plus d\'appels) apparaissent souvent en 2 à 4 semaines. L\'amélioration du classement dans le pack local se manifeste en 4 à 8 semaines, avec un saut plus net entre 2 et 4 mois si vous maintenez la collecte d\'avis et la publication de contenu.' },
    ],
  },
  'plaque-nfc-institut-beaute': {
    title: 'Plaque NFC institut de beauté : placement et script',
    description: 'Instituts de beauté, onglerie, spa : collectez des avis Google avec une plaque NFC. Guide 2026 : emplacements, scripts et exemples de calcul.',
    keywords: 'plaque nfc institut de beaute, avis google institut de beaute, plaque nfc esthetique, avis google estheticienne, plaque nfc onglerie, avis google spa, seo local institut beaute',
    date: '2026-07-22',
    dateModified: '2026-07-28',
    category: 'Secteur',
    faq: [
      { q: 'Combien d\'avis Google un institut peut-il collecter avec une plaque NFC ?', a: 'Un institut recevant 30 à 40 clientes par semaine passe généralement de 3-6 avis/mois à 15-30 avis/mois, soit une multiplication par 4 à 6. Les bars à ongles à forte rotation dépassent souvent 35 avis par mois.' },
      { q: 'Où placer la plaque NFC dans un institut de beauté ?', a: 'Le comptoir de caisse est le meilleur emplacement (35-45 % de conversion) : la cliente a déjà son téléphone en main pour régler et vient de vivre un moment agréable. La table de manucure (25-35 %) et la cabine près du miroir (20-30 %) sont d\'excellents compléments.' },
      { q: 'La plaque résiste-t-elle aux crèmes, vernis et à l\'humidité ?', a: 'Oui. L\'acrylique premium 3 mm résiste à l\'eau, aux UV, aux rayures et aux projections. Un simple coup de chiffon suffit à la nettoyer, contrairement à une affiche papier ou un flyer plastifié qui devient vite illisible.' },
      { q: 'Puis-je offrir une remise ou un soin en échange d\'un avis ?', a: 'Non, c\'est formellement interdit par les règles de Google. Vos avis pourraient être supprimés en masse et votre fiche suspendue. La plaque NFC fonctionne en supprimant la friction, pas en achetant l\'avis.' },
      { q: 'Faut-il un abonnement pour la plaque NFC ?', a: 'Non. La plaque Swiipx est un paiement unique : elle fonctionne pendant des années sans frais récurrents ni renouvellement mensuel.' },
      { q: 'Quel pack choisir pour un institut de beauté ?', a: 'Institut mono-poste : Pack Starter. Institut avec caisse et cabine ou table de manucure : Pack Business (2 plaques), la configuration la plus courante. Spa ou institut multi-cabines : Pack Pro (5 plaques).' },
    ],
  },
  'comment-choisir-plaque-nfc-avis-google': {
    title: 'Choisir sa plaque NFC avis Google en 2026',
    description: 'Choisir sa plaque NFC avis Google : puce NTAG215, matériau, nombre de plaques. 7 critères, comparatif et pièges à éviter. Guide d\'achat 2026.',
    keywords: 'choisir plaque nfc, plaque nfc avis google, guide achat plaque nfc, puce ntag215, plaque nfc sans abonnement, meilleure plaque nfc avis google, comparatif plaque nfc',
    date: '2026-07-20',
    dateModified: '2026-07-28',
    category: 'Comparatif',
    faq: [
      { q: 'Quelle puce NFC choisir pour une plaque avis Google ?', a: 'La NTAG215 (504 octets) est le bon standard : elle ouvre la fiche Google instantanement et est compatible avec tous les iPhone depuis 2016 et la quasi-totalite des Android. Evitez la NTAG213 des modeles bas de gamme et exigez toujours que la reference de puce soit precisee.' },
      { q: 'Faut-il payer un abonnement pour une plaque NFC ?', a: 'Non, et c\'est le principal piege a eviter. Une bonne plaque fonctionne a vie apres un paiement unique de 35 a 60 EUR. Les formules avec abonnement mensuel coutent 15 a 25 fois plus cher sur 5 ans pour un service identique, et rendent la plaque inutilisable si vous arretez de payer.' },
      { q: 'Quel materiau est le plus durable pour une plaque NFC ?', a: 'L\'acrylique premium de 3 mm : il resiste a l\'eau, aux UV, aux rayures et aux projections de graisse, et garde un rendu premium pendant des annees. Le PVC fin jaunit et se raye, le bois craint l\'humidite, et le metal peut gener le signal NFC s\'il est mal concu.' },
      { q: 'Combien de plaques NFC faut-il pour mon commerce ?', a: 'Comptez une plaque par point de contact ou le client a son telephone en main apres une experience positive. Un point de caisse unique : Pack Starter. Caisse plus accueil : Pack Business (2 plaques), la configuration la plus courante. Multi-postes ou multi-salles : Pack Pro (5 plaques).' },
      { q: 'La plaque NFC fonctionne-t-elle sur tous les telephones ?', a: 'Oui pour la quasi-totalite : tous les iPhone depuis 2016 et la grande majorite des Android lisent le NFC. Pour les rares appareils sans NFC actif (5 a 10 %), un QR code de secours imprime sur la plaque permet quand meme de laisser un avis. Exigez ce QR code a l\'achat.' },
      { q: 'Quel est le bon budget pour une plaque NFC avis Google ?', a: 'Entre 35 et 60 EUR par plaque en paiement unique. En dessous de 15 EUR, la qualite (puce, materiau, QR de secours) n\'y est generalement pas. Le retour sur investissement est atteint des le premier ou deuxieme client supplementaire grace aux nouveaux avis collectes.' },
    ],
  },
  'statistiques-avis-google-2026': {
    title: 'Statistiques avis Google 2026 : 45 chiffres clés',
    description: '45 statistiques 2026 sur les avis Google : comportement des consommateurs, impact SEO local, conversion et effet de la note.',
    keywords: 'statistiques avis google, chiffres avis google 2026, avis google seo local, impact avis clients, statistiques avis clients, note google etoiles, taux conversion avis, pack local google',
    date: '2026-07-17',
    dateModified: '2026-07-28',
    category: 'Statistiques',
    faq: [
      { q: 'Quel pourcentage de consommateurs lisent les avis Google avant d\'acheter ?', a: 'En 2026, environ 93 % des consommateurs consultent les avis en ligne avant de choisir un commerce local, et 87 % font spécifiquement confiance à Google, de loin la première plateforme d\'avis devant les réseaux sociaux et les annuaires spécialisés.' },
      { q: 'Combien d\'avis Google faut-il pour être crédible ?', a: 'Le seuil psychologique se situe autour de 40 à 50 avis : en dessous, la note est jugée peu fiable. Pour peser dans le pack local face à la concurrence, il faut généralement dépasser 100 avis. Le volume et la régularité comptent autant que la note elle-même.' },
      { q: 'Quel est l\'impact d\'une étoile supplémentaire sur le chiffre d\'affaires ?', a: 'Les études convergent : gagner une étoile (par exemple passer de 3,5 à 4,5) augmente le chiffre d\'affaires de 5 à 9 % pour un commerce local, principalement via une hausse du taux de clic et de conversion depuis Google Maps.' },
      { q: 'Les avis récents comptent-ils plus que les anciens ?', a: 'Oui. 73 % des consommateurs estiment qu\'un avis de plus de trois mois n\'est plus pertinent, et Google pondère la fraîcheur dans son classement local. Une fiche qui collecte des avis chaque semaine surperforme une fiche figée, même mieux notée.' },
      { q: 'Faut-il répondre aux avis pour le référencement ?', a: 'Oui, indirectement mais réellement. 89 % des consommateurs lisent les réponses du gérant, et les fiches actives voient leur taux de clic augmenter de 15 à 25 %. Google valorise l\'engagement du gérant comme un signal de fiche vivante et légitime.' },
      { q: 'Quelle méthode de collecte d\'avis convertit le mieux ?', a: 'La plaque NFC convertit 35 à 45 % des clients sollicités, contre 8 à 12 % pour un QR code seul, 5 à 8 % pour un SMS et 1 à 3 % pour une carte de visite. La suppression de la friction au moment du paiement explique cet écart.' }
    ],
  },
  'repondre-avis-negatifs-google': {
    title: 'Répondre aux avis négatifs Google : méthode 2026',
    description: 'Répondre aux avis négatifs Google : méthode en 5 étapes, 6 modèles prêts à l\'emploi et procédure de suppression. Guide 2026.',
    keywords: 'repondre avis negatif google, avis negatif google, supprimer avis google, reponse avis google, gerer avis negatifs, modele reponse avis negatif, e-reputation locale, google business profile avis',
    date: '2026-07-13',
    dateModified: '2026-07-28',
    category: 'SEO Local',
    faq: [
      { q: 'Faut-il répondre à tous les avis négatifs ?', a: 'Oui, sans exception. Un avis négatif sans réponse est interprété par les lecteurs comme un aveu. Répondez aussi aux avis à 1 étoile sans commentaire, en invitant poliment la personne à préciser son problème.' },
      { q: 'En combien de temps faut-il répondre à un avis négatif ?', a: 'Sous 24 à 48 heures maximum. Passé une semaine, la réponse perd l\'essentiel de son effet : le taux de modification de l\'avis par le client tombe de 30-40 % à moins de 8 %.' },
      { q: 'Peut-on faire supprimer un avis Google négatif ?', a: 'Uniquement s\'il viole les règles de Google : contenu injurieux, spam, avis d\'un concurrent, conflit d\'intérêts, informations personnelles ou avis d\'une personne qui n\'a jamais été cliente. Un avis simplement injuste ne sera pas supprimé : moins de 20 % des signalements aboutissent.' },
      { q: 'Que faire face à un avis manifestement faux ?', a: 'Répondez publiquement de façon factuelle et calme, par exemple en indiquant que vous ne retrouvez aucune trace du passage de cette personne, puis signalez l\'avis via les trois points puis Signaler comme inapproprié. Ne l\'attaquez jamais frontalement.' },
      { q: 'Les réponses aux avis améliorent-elles le référencement local ?', a: 'Oui, indirectement mais réellement. Elles ajoutent du contenu textuel indexable à votre fiche, envoient un signal de fraîcheur à Google et augmentent le taux de clic de 15 à 25 %. Elles ne remplacent toutefois pas le volume d\'avis, premier critère du pack local.' },
      { q: 'Comment limiter l\'impact d\'un avis négatif ?', a: 'En augmentant votre volume d\'avis positifs. Un avis à 1 étoile fait chuter une note de 4,5 à 4,33 quand vous avez 20 avis, mais seulement à 4,49 avec 300 avis. Une plaque NFC convertit 35 à 45 % des clients sollicités et permet de noyer un avis négatif en quelques jours.' },
    ],
  },
  'plaque-nfc-garage-automobile': {
    title: 'Plaque NFC garage auto : placement et script atelier',
    description: 'Garages, centres auto, carrosseries : collectez des avis Google avec une plaque NFC. Guide 2026 : emplacements, scripts garagiste, exemples de calcul.',
    keywords: 'plaque nfc garage, avis google garage, plaque nfc garage automobile, avis google garagiste, plaque avis google centre auto, avis google carrosserie, seo local garage',
    date: '2026-07-13',
    dateModified: '2026-07-28',
    category: 'Secteur',
    faq: [
      { q: 'Combien d\'avis Google un garage peut-il collecter avec une plaque NFC ?', a: 'Un garage traitant 15 à 20 véhicules par semaine passe généralement de 2-4 avis/mois à 12-25 avis/mois, soit une multiplication par 4 à 6. Les centres auto à fort volume dépassent souvent 40 avis par mois.' },
      { q: 'Où placer la plaque NFC dans un garage ?', a: 'Le comptoir de facturation est le meilleur emplacement (35-45 % de conversion) : le client a déjà son téléphone en main pour payer et vient de récupérer son véhicule. L\'accueil arrive en second (20-30 %), puis la salle d\'attente (10-15 %).' },
      { q: 'La plaque résiste-t-elle à l\'environnement d\'un atelier ?', a: 'Oui. L\'acrylique premium 3 mm résiste à l\'eau, aux UV, aux rayures et aux projections d\'huile. Un simple coup de chiffon suffit à la nettoyer, contrairement à une affiche papier ou un flyer plastifié.' },
      { q: 'Puis-je offrir une remise en échange d\'un avis Google ?', a: 'Non, c\'est formellement interdit par les règles de Google. Vos avis pourraient être supprimés en masse et votre fiche suspendue. La plaque NFC fonctionne en supprimant la friction, pas en achetant l\'avis.' },
      { q: 'Quel pack de plaques choisir pour un garage ?', a: 'Garage indépendant avec un seul point de caisse : Pack Starter. Garage avec accueil et caisse séparés : Pack Business (2 plaques), la configuration la plus courante. Centre auto multi-baies : Pack Pro (5 plaques).' },
      { q: 'Combien de temps avant de voir un effet sur Google ?', a: 'Les premiers avis arrivent dès la première semaine. L\'effet sur le classement dans le pack local se manifeste en 4 à 8 semaines, avec un saut significatif entre 3 et 6 mois si le rythme est maintenu.' },
    ],
  },
  'plaque-nfc-cabinet-medical': {
    title: 'Plaque NFC cabinet médical : avis & règles',
    description: 'Médecins, dentistes, kinés : collectez des avis Google avec une plaque NFC en respectant la déontologie. Guide 2026 : placements et scripts conformes.',
    keywords: 'plaque nfc cabinet medical, avis google dentiste, avis google medecin, plaque nfc dentiste, avis google kinesitherapeute, plaque nfc osteopathe, deontologie avis google',
    date: '2026-06-08',
    dateModified: '2026-07-28',
    category: 'Secteur',
    faq: [
      { q: 'Est-ce déontologique de demander des avis à ses patients ?', a: 'Oui, à condition de rester passif et non insistant, sans contrepartie ni tri des patients. La plaque NFC est un moyen passif : le patient choisit librement de l\'utiliser ou non, ce qui est conforme aux recommandations des ordres professionnels.' },
      { q: 'Puis-je répondre aux avis de mes patients ?', a: 'Oui, mais sans jamais révéler d\'information de santé ni confirmer qu\'une personne est votre patient (secret médical). Restez neutre : "Merci pour votre retour" suffit. Ne mentionnez jamais le motif de consultation.' },
      { q: 'Combien d\'avis un cabinet médical peut-il espérer collecter ?', a: 'Un cabinet moyen passe de 5-10 avis/an à 30-60 avis/an avec une plaque NFC bien placée, soit une multiplication par 4 à 6, tout en respectant la discrétion attendue dans le secteur médical.' },
      { q: 'Où placer la plaque NFC dans un cabinet médical ?', a: 'Le meilleur emplacement est sur le bureau, évoqué une seule fois en fin de consultation (25-35 % de conversion). À l\'accueil/secrétariat au moment de reprendre rendez-vous (15-25 %). En salle d\'attente de façon discrète (10-15 %).' },
      { q: 'Faut-il un abonnement pour la plaque NFC ?', a: 'Non. La plaque Swiipx fonctionne sans abonnement : un paiement unique et elle fonctionne pendant des années, sans frais récurrents ni renouvellement mensuel.' },
    ],
  },
  'plaque-nfc-restaurant': {
    title: 'Plaque NFC restaurant : placement et scripts de service',
    description: 'Restaurant : collecter des avis Google avec une plaque NFC, sans interrompre le service. Guide 2026 : placements en salle, scripts serveur, exemples de calcul.',
    keywords: 'plaque nfc restaurant, avis google restaurant, plaque avis google restaurant, plaque nfc bistrot, nfc restauration, avis restaurant google, collecte avis restaurant',
    date: '2026-05-11',
    dateModified: '2026-07-28',
    category: 'Secteur',
    faq: [
      { q: 'Combien d\'avis Google peut collecter un restaurant avec une plaque NFC ?', a: 'Un restaurant moyen (30 couverts/jour) passe de 5-8 avis/mois à 25-40 avis/mois grâce à une plaque NFC, soit une multiplication par 4-7. Les meilleurs résultats observés atteignent 60 avis/mois sur des brasseries 80+ couverts.' },
      { q: 'Où placer la plaque NFC dans un restaurant ?', a: 'Le meilleur emplacement est sur la table (placée à côté du sel ou sur le porte-addition), avec un taux de conversion de 40-50 %. Le 2e meilleur emplacement est à la caisse à côté du terminal de paiement (25-35 %).' },
      { q: 'Le serveur doit-il mentionner la plaque ?', a: 'Oui, c\'est crucial. Une plaque sans mention verbale convertit 3-4 fois moins. Le script optimal : "Tout s\'est bien passé ? Si vous avez 30 secondes, un avis Google nous aiderait beaucoup. Approchez juste votre téléphone ici."' },
      { q: 'Quel pack de plaques pour un restaurant ?', a: 'Petit resto (15-30 couverts) : Pack Starter 1 plaque. Restaurant moyen (30-60 couverts) : Pack Business 2 plaques. Grande brasserie (60+ couverts) : Pack Pro 5 plaques.' },
      { q: 'Combien de temps pour voir l\'impact sur Google ?', a: 'Nouveaux avis dès la 1ère semaine. Impact sur le ranking pack local en 4-8 semaines. Saut significatif visible à 3-6 mois en maintenant le rythme.' },
    ],
  },
  'plaque-avis-google-sans-abonnement': {
    title: 'Plaque avis Google sans abonnement : le top 5',
    description: 'Plaque avis Google sans abonnement : comparatif honnête de 5 marques en 2026. Prix, qualité, fonctionnalités. Économisez 500-1500 € sur 5 ans.',
    keywords: 'plaque avis google sans abonnement, plaque nfc sans abonnement, plaque google paiement unique, comparatif plaque nfc, plaque sans engagement, plaque avis sans abonnement',
    date: '2026-05-11',
    dateModified: '2026-07-28',
    category: 'Comparatif',
    faq: [
      { q: 'Pourquoi choisir une plaque NFC sans abonnement ?', a: 'Une plaque NFC est un objet physique qui fonctionne 10 ans sans maintenance. L\'abonnement (9-29 €/mois) n\'apporte rien techniquement et coûte 500-1500 € de plus sur 5 ans pour des fonctionnalités identiques.' },
      { q: 'Combien économise-t-on en choisissant sans abonnement ?', a: 'En moyenne 500 à 1 500 € par plaque sur 5 ans. Pour un commerce avec 5 plaques, l\'économie peut atteindre 5 000 € sur 5 ans, soit l\'équivalent d\'un mois de loyer commercial.' },
      { q: 'Une plaque sans abonnement est-elle de moins bonne qualité ?', a: 'Non, c\'est un mythe. La qualité dépend du fabricant, pas du modèle économique. Les marques sans abonnement (Swiipx, Cogimix) utilisent les mêmes puces NTAG215 que les marques avec abonnement.' },
      { q: 'Si la marque "sans abonnement" disparaît dans 2 ans ?', a: 'Aucun impact. La plaque physique continue de fonctionner indépendamment de la marque. Elle redirige vers votre URL Google qui, elle, est permanente. Pas de cloud ou serveur à maintenir.' },
      { q: 'Quelle est la meilleure marque sans abonnement en France ?', a: 'Selon notre comparatif 2026, Swiipx offre le meilleur rapport qualité-prix : acrylique 3 mm, NTAG215, QR de secours, garantie à vie, personnalisation incluse, à 35,88 €.' },
    ],
  },
  'plaque-nfc-salon-coiffure': {
    title: 'Plaque NFC salon coiffure : ROI réel + guide 2026',
    description: 'Salon de coiffure : comment collecter +150 avis Google/an avec une plaque NFC. Placements, scripts, études de cas réelles, ROI x300.',
    keywords: 'plaque nfc salon coiffure, plaque avis google coiffeur, nfc institut beauté, avis google salon, plaque nfc beauté, collecte avis coiffeur, plaque nfc barbier',
    date: '2026-05-11',
    dateModified: '2026-07-28',
    category: 'Secteur',
    faq: [
      { q: 'Pourquoi les salons sont-ils idéaux pour la plaque NFC ?', a: 'Les salons offrent le contexte parfait : clientes captives 60-90 min, satisfaites en fin de service (transformation visible), téléphone à portée. Taux de conversion record : 40-55 % (vs 20-30 % dans d\'autres secteurs).' },
      { q: 'Où placer la plaque dans un salon de coiffure ?', a: 'Le meilleur emplacement est sur le poste de coiffage (à côté du miroir) : taux de conversion 45-55 %. Le 2e emplacement optimal : à côté du miroir d\'accueil ou à la caisse (30-40 %).' },
      { q: 'Quel script pour demander un avis dans un salon ?', a: 'Le script à 55 % : "Vous êtes magnifique ! Si ça vous plaît, j\'ai une petite faveur : un avis Google nous aide vraiment. Approchez juste votre téléphone ici, ça prend 30 secondes !"' },
      { q: 'Combien de plaques pour un salon de coiffure ?', a: 'Petit salon (1-2 fauteuils) : 1 plaque (poste principal). Salon moyen (3-4 fauteuils) : 2 plaques (1 poste + 1 caisse). Institut multi-cabines : 5 plaques (1 par cabine).' },
      { q: 'Mes clientes seniors comprennent-elles le NFC ?', a: 'Oui. Le NFC fonctionne sur tout smartphone récent (iPhone 7+ depuis 2016, Android post-2018). La cliente n\'a rien à comprendre techniquement : elle approche son téléphone, ça s\'ouvre automatiquement. Plus simple qu\'un QR code.' },
    ],
  },
  'prix-plaque-nfc-avis-google': {
    title: 'Prix plaque NFC avis Google : le vrai budget',
    description: 'Prix d\'une plaque NFC avis Google en 2026 : fourchettes par qualité, packs multi-plaques, facteurs de prix. Le bon budget : 35-60 € par plaque.',
    keywords: 'prix plaque nfc avis google, combien coute plaque nfc, tarif plaque avis google, plaque nfc pas cher, prix plaque google, cout plaque nfc avis',
    date: '2026-05-12',
    dateModified: '2026-07-28',
    category: 'Comparatif',
    faq: [
      { q: 'Quel est le bon prix pour une plaque NFC professionnelle en 2026 ?', a: 'Entre 35 et 50 € pour une plaque pro de qualité : acrylique 3 mm, NTAG215, QR de secours, garantie à vie, personnalisation incluse. En dessous, qualité douteuse. Au-dessus, vous payez surtout l\'esthétique.' },
      { q: 'Pourquoi certaines plaques NFC coûtent moins de 20 € ?', a: 'Production de masse en Asie avec puces NTAG213 bas de gamme, PVC fin, pas de QR de secours, pas de SAV. Économie à court terme mais durée de vie réelle de 6-18 mois vs 10 ans pour une plaque pro.' },
      { q: 'Faut-il un abonnement mensuel ?', a: 'Non. Une plaque NFC fonctionne 10 ans sans maintenance. Les abonnements (9-29 €/mois) facturent un dashboard analytics inutile (Google Business Profile donne déjà ces stats gratuitement).' },
      { q: 'Quelle économie sur un pack multi-plaques ?', a: 'Économie d\'échelle : 2 plaques = environ 17 % de moins que le prix unitaire ×2, 5 plaques = environ 47 % de moins. Ex. Swiipx : 1 plaque 35,88 €, 2 plaques 65,88 € (économie 9,80 €), 5 plaques 107,88 € (économie 69,60 €).' },
      { q: 'En combien de temps une plaque NFC est-elle amortie ?', a: 'Pour 99 % des commerces locaux, une plaque NFC à 40-60 € s\'amortit en moins de 7 jours grâce à 3-5 nouveaux clients/mois acquis via les nouveaux avis Google et la meilleure visibilité dans le pack local.' },
    ],
  },
  'ou-placer-plaque-avis-google': {
    title: 'Où placer sa plaque avis Google ? 7 endroits',
    description: 'Le placement de votre plaque avis Google détermine 80 % du taux de conversion. Guide 2026 : 7 emplacements optimaux par secteur (restaurant, salon, retail).',
    keywords: 'où placer plaque avis google, emplacement plaque nfc, placement plaque avis google, position plaque nfc, optimiser plaque nfc, placer plaque nfc',
    date: '2026-05-12',
    dateModified: '2026-07-28',
    category: 'Conseils',
    faq: [
      { q: 'Pourquoi le placement de la plaque NFC est-il si important ?', a: 'Le placement détermine 80 % du taux de conversion. Une même plaque mal placée convertit 5 %, bien placée convertit 45 %. La visibilité, le timing (moment de satisfaction maximale) et l\'accessibilité physique sont les 3 facteurs clés.' },
      { q: 'Quel est le meilleur emplacement universel ?', a: 'Le top 1 : sur la table / poste de travail individuel (40-55 % de conversion). Le client voit la plaque pendant tout le service et son téléphone est à portée au moment du paiement.' },
      { q: 'Peut-on mettre une plaque NFC en extérieur ?', a: 'Oui pour les plaques en acrylique 3 mm de qualité. Résistantes à la pluie, aux UV, aux températures de -10 à +60 °C. Utile pour les terrasses de café/restaurant.' },
      { q: 'La plaque peut-elle être collée sur du métal ?', a: 'Évitez. Le métal interfère avec le signal NFC (effet cage de Faraday). Si nécessaire, intercalez une protection isolante. Mieux : choisissez un support en bois, verre, plastique ou plâtre.' },
      { q: 'Combien de temps avant de tester un nouvel emplacement ?', a: 'Minimum 2-4 semaines à chaque emplacement avant de juger. La conversion dépend du volume client qui varie selon la semaine. Une mesure sur trop courte période est trompeuse.' },
    ],
  },
  'plaque-nfc-vs-qr-code-avis-google': {
    title: 'Plaque NFC ou QR code : lequel convertit ?',
    description: 'Plaque NFC ou QR code pour collecter des avis Google ? Comparatif 2026 : taux de conversion (35-45 % vs 8-12 %), prix, compatibilité, ROI.',
    keywords: 'plaque nfc vs qr code, qr code avis google, plaque nfc avis google, comparatif nfc qr, avis google nfc, taux conversion qr code, plaque nfc france, comparer nfc qr',
    date: '2026-05-10',
    dateModified: '2026-07-28',
    category: 'Comparatif',
    faq: [
      { q: 'Plaque NFC ou QR code : lequel convertit le plus d\'avis Google ?', a: 'La plaque NFC convertit 4 fois mieux que le QR code : 35-45 % de taux de conversion contre 8-12 % pour le QR. Cette différence s\'explique par la friction réduite (2 étapes vs 5 étapes) et l\'absence de décision consciente du client.' },
      { q: 'La plaque NFC fonctionne-t-elle sur tous les iPhone ?', a: 'Oui, sur tous les iPhone depuis l\'iPhone 7 (2016). Depuis iOS 14 (2020), le NFC en arrière-plan est natif : aucune application à ouvrir, le téléphone détecte automatiquement la plaque.' },
      { q: 'Quel est le coût comparé d\'une plaque NFC vs un QR code ?', a: 'Une plaque NFC coûte 35-50 € avec une durée de vie de 10+ ans, soit environ 4 € par an. Un autocollant QR code coûte 5 € mais doit être renouvelé tous les 1-2 ans (sensibilité à l\'usure), soit 3-5 € par an. Coûts annuels quasi-identiques mais expérience NFC très supérieure.' },
      { q: 'Peut-on combiner plaque NFC et QR code ?', a: 'Oui, c\'est même recommandé. Les plaques NFC professionnelles intègrent un QR code de secours imprimé. Cela couvre les 5 % de smartphones non-NFC tout en bénéficiant du taux de conversion premium du NFC pour les 95 % restants.' },
      { q: 'En combien de temps une plaque NFC est-elle rentabilisée ?', a: 'Une plaque NFC à 40 € est typiquement rentabilisée en 2 à 4 semaines pour un commerce moyen, grâce à 3-5 nouveaux clients/mois acquis via les nouveaux avis Google et la meilleure visibilité dans le pack local.' },
    ],
  },
  'obtenir-plus-avis-google': {
    title: 'Obtenir plus d\'avis Google : 10 méthodes',
    description: '10 méthodes testées pour obtenir plus d\'avis Google rapidement (+250 % en 3 mois). NFC, QR code, scripts email/SMS : guide pratique 2026.',
    keywords: 'obtenir avis google, plus avis google, augmenter avis google, collecte avis, méthodes avis google, NFC avis, QR code avis, script demande avis',
    date: '2026-01-15',
    dateModified: '2026-07-28',
    category: 'Stratégie',
    faq: [
      { q: 'Quelle est la méthode la plus efficace pour obtenir des avis Google ?', a: 'La plaque NFC est la méthode la plus efficace avec un taux de conversion de 35-45 %, car elle supprime toute friction. Le client approche son téléphone et arrive directement sur la page d\'avis Google.' },
      { q: 'Combien d\'avis Google faut-il pour être visible ?', a: 'Un minimum de 20-30 avis est recommandé pour apparaître dans le pack local. Au-delà de 50 avis, votre visibilité augmente significativement. L\'objectif est de maintenir un flux régulier d\'avis récents.' },
      { q: 'Est-il légal de demander des avis Google à ses clients ?', a: 'Oui, demander des avis est parfaitement légal et conforme aux règles de Google. Ce qui est interdit, c\'est d\'offrir une contrepartie (réduction, cadeau) en échange d\'un avis ou de rédiger de faux avis.' },
      { q: 'Peut-on utiliser plusieurs méthodes de collecte en même temps ?', a: 'Oui, c\'est même recommandé. Combinez le NFC en point de vente avec l\'email de suivi et le SMS pour maximiser votre taux de collecte. Chaque canal touche le client à un moment différent.' },
    ],
  },
  'avis-clients-influencent-business': {
    title: 'L\'impact réel des avis clients sur votre CA',
    description: 'Impact des avis Google sur le chiffre d\'affaires, la conversion et le SEO local. Données 2026, stratégies par secteur et calcul du ROI.',
    keywords: 'avis clients business, impact avis google, avis et chiffre affaires, avis clients conversion, e-réputation, gestion avis négatifs, ROI avis google',
    date: '2025-11-08',
    dateModified: '2026-07-28',
    category: 'Business',
    faq: [
      { q: 'Quel est l\'impact des avis Google sur le chiffre d\'affaires ?', a: 'Passer de 3,5 à 4,5 étoiles sur Google entraîne une augmentation moyenne de 25 % du chiffre d\'affaires. Les entreprises avec plus de 50 avis génèrent 3 fois plus de clics que celles avec moins de 10 avis.' },
      { q: 'Comment les avis influencent-ils le SEO local ?', a: 'Google utilise le volume, la fréquence et la qualité des avis comme facteur de classement dans le pack local. Les fiches avec des avis récents et des réponses du propriétaire sont favorisées dans les résultats de recherche.' },
      { q: 'Faut-il répondre aux avis négatifs ?', a: 'Oui, toujours. 89 % des prospects lisent les réponses aux avis négatifs. Une réponse professionnelle et empathique peut transformer un avis négatif en démonstration de votre sérieux et de votre engagement client.' },
      { q: 'Quel est le nombre minimum d\'avis pour inspirer confiance ?', a: 'Les études montrent qu\'un minimum de 10 avis est nécessaire pour que les consommateurs considèrent la note comme fiable. Au-delà de 40 avis, l\'effet de confiance atteint son maximum.' },
    ],
  },
  'booster-visibilite-locale': {
    title: 'Booster sa visibilité locale : 5 astuces',
    description: 'Dominer le pack local Google : optimisation Google Business Profile, avis, citations NAP, pages locales, backlinks. Plan d\'action 30/60/90 jours.',
    keywords: 'visibilité locale, SEO local, pack local google, Google Business Profile, citations NAP, avis google local, référencement local, backlinks locaux',
    date: '2025-11-05',
    dateModified: '2026-07-28',
    category: 'SEO Local',
    faq: [
      { q: 'Combien de temps faut-il pour apparaître dans le pack local Google ?', a: 'Avec une stratégie active (fiche optimisée, collecte d\'avis, citations), vous pouvez commencer à apparaître dans le pack local en 4 à 8 semaines. Les résultats s\'accélèrent à partir du 3e mois.' },
      { q: 'Qu\'est-ce que le NAP et pourquoi est-ce important ?', a: 'NAP signifie Name, Address, Phone. La cohérence de ces informations sur tous les annuaires en ligne est un facteur de classement majeur pour Google. Toute incohérence peut nuire à votre visibilité locale.' },
      { q: 'Faut-il un site web pour apparaître dans le pack local ?', a: 'Non, la fiche Google Business Profile suffit pour apparaître dans le pack local. Cependant, un site web avec des pages locales optimisées renforce considérablement votre positionnement et vos chances d\'apparaître en première position.' },
      { q: 'Combien d\'avis faut-il pour dominer le pack local ?', a: 'Il n\'y a pas de nombre fixe, car cela dépend de la concurrence locale. En règle générale, avoir 20-30 % d\'avis de plus que le concurrent le mieux placé vous donne un avantage significatif.' },
    ],
  },
  'nfc-avis-clients': {
    title: 'NFC et avis clients : le guide complet 2026',
    description: 'Collecter plus d\'avis Google avec une plaque NFC : fonctionnement, taux de conversion (35-45 %), mise en place et ROI. Guide 2026.',
    keywords: 'NFC avis clients, plaque NFC avis google, collecte avis NFC, NFC vs QR code, plaque avis restaurant, NFC commerce, avis google automatique',
    date: '2025-11-02',
    dateModified: '2026-07-28',
    category: 'Technologie',
    faq: [
      { q: 'Comment fonctionne une plaque NFC pour les avis Google ?', a: 'La plaque NFC contient une puce programmée avec le lien direct vers votre page d\'avis Google. Quand un client approche son smartphone, le lien s\'ouvre automatiquement sans application ni scan. Le client n\'a plus qu\'à rédiger son avis et publier.' },
      { q: 'Le NFC fonctionne-t-il avec tous les smartphones ?', a: 'Oui. Tous les iPhone depuis le modèle 7 (2016) et la quasi-totalité des smartphones Android supportent le NFC nativement. Cela couvre plus de 95 % des appareils en circulation en France.' },
      { q: 'Quelle est la différence entre NFC et QR code pour les avis ?', a: 'Le NFC convertit à 35-45 % contre 8-12 % pour le QR code. La raison : le NFC ne nécessite aucune action de la part du client (pas d\'appareil photo à ouvrir, pas de lien à cliquer). C\'est un simple contact physique.' },
      { q: 'Où placer la plaque NFC dans mon commerce ?', a: 'L\'emplacement idéal dépend de votre métier. Restaurant : sur la table ou à la caisse. Salon de coiffure : devant le miroir. Cabinet médical : à l\'accueil. Boutique : au comptoir. Le principe : là où le client est le plus satisfait.' },
      { q: 'Google pénalise-t-il les avis collectés par NFC ?', a: 'Non. Le NFC redirige simplement vers la page d\'avis Google officielle. Le client rédige son propre avis librement. Aucune manipulation, aucune incitation interdite. Cette méthode est 100 % conforme aux règles de Google.' },
    ],
  },
  'seo-local-recherches-google': {
    title: 'SEO local : passer en tête de Google Maps',
    description: 'Méthode 2026 pour gagner le pack local Google Maps : Google Business Profile, avis, pages locales, citations NAP, backlinks. Plan d\'action 30 jours.',
    keywords: 'SEO local, référencement local, pack local google, google maps seo, Google Business Profile, schema LocalBusiness, citations NAP, backlinks locaux, visibilité locale',
    date: '2025-10-28',
    dateModified: '2026-07-28',
    category: 'SEO Local',
    faq: [
      { q: 'Qu\'est-ce que le SEO local et pourquoi est-ce important ?', a: 'Le SEO local est l\'ensemble des techniques pour apparaître dans les résultats de recherche géolocalisés (pack local, Google Maps). C\'est crucial car 46 % des recherches Google ont une intention locale et 88 % des recherches locales sur mobile mènent à une visite ou un appel sous 24h.' },
      { q: 'Quels sont les 3 facteurs de classement SEO local de Google ?', a: 'Google classe les résultats locaux selon 3 critères : la pertinence (votre fiche correspond-elle à la recherche), la distance (proximité avec l\'utilisateur) et la notoriété (avis, citations, backlinks, ancienneté).' },
      { q: 'Combien de temps prend une stratégie SEO local pour donner des résultats ?', a: 'Les premiers résultats apparaissent généralement en 4 à 8 semaines. Une progression significative dans le pack local prend 3 à 6 mois avec une stratégie active et régulière.' },
      { q: 'Faut-il utiliser le schema markup pour le SEO local ?', a: 'Oui, le schema LocalBusiness aide Google à mieux comprendre votre activité, votre zone de service et vos coordonnées. Il augmente aussi vos chances d\'obtenir des rich snippets dans les résultats de recherche.' },
    ],
  },
  'erreurs-demander-avis': {
    title: 'Avis Google : les 7 erreurs qui font bannir',
    description: 'Acheter des faux avis, offrir des récompenses, harceler les clients : les erreurs qui font bannir votre fiche Google. Guide complet 2026.',
    keywords: 'erreurs avis google, faux avis google, acheter avis google, avis google interdits, règles avis google, sanctions google avis, bonnes pratiques avis',
    date: '2025-10-25',
    dateModified: '2026-07-28',
    category: 'Bonnes pratiques',
    faq: [
      { q: 'Que risque-t-on en achetant des faux avis Google ?', a: 'Google peut supprimer tous vos avis (même les vrais), suspendre votre fiche Google Business Profile et vous infliger une pénalité de visibilité durable. La FTC et la DGCCRF peuvent aussi imposer des amendes pour pratiques commerciales trompeuses.' },
      { q: 'Peut-on offrir une réduction en échange d\'un avis Google ?', a: 'Non, c\'est explicitement interdit par les conditions d\'utilisation de Google. Offrir une contrepartie (réduction, cadeau, avantage) en échange d\'un avis est considéré comme de l\'incentivization et peut entraîner la suppression de tous vos avis.' },
      { q: 'Comment supprimer un faux avis négatif sur Google ?', a: 'Signalez l\'avis via votre fiche Google Business Profile en sélectionnant le motif approprié (spam, contenu hors sujet, conflit d\'intérêts). Google examine le signalement sous 3 à 15 jours. En attendant, répondez professionnellement à l\'avis.' },
      { q: 'Est-ce une erreur de ne pas répondre aux avis ?', a: 'Oui, c\'est une erreur majeure. Ne pas répondre envoie un signal de désintérêt à vos prospects. Google favorise aussi les fiches dont le propriétaire répond activement aux avis. Répondez à chaque avis, positif comme négatif, sous 24 à 48h.' },
    ],
  },
}
